
name: Pet Store API Automation 

on:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
env:
  BackEndTesting  RESULTS_DIRECTORY: ./.github/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          distribution: 'temurin'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./mvnw


  test_backend:
    name:  Automation
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Backend Tests
        run: |
          ./mvnw clean install 

      - name:  Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: PetStore/build/reports/tests/test
